development:
  clients:
    default:
      database: new_fitclubs_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: new_fitclubs_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

staging:
  clients:
    default:
      database: new_fitclubs_staging
      hosts:
        - localhost:27017
